### ISSUE TITLE
Issue using search_datasets and get_collection

### ISSUE THREAD

**Issue by Noa164** [ropensci/rmangal#101]
After I'd downloaded the package using ``` remotes::install_github("ropensci/rmangal")```. I proceeded to use the package 
```
library("rmangal")
datasets<-search_datasets(list(ref_id = 141))
datasets<-get_collection(datasets)
> datasets<-search_datasets(list(ref_id = 141))
Error in curl::curl_fetch_memory(url, handle = handle) : 
  LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to mangal.io:443
```

the package worked for me in the past without issues.

thank you in advance,
Noa Frydman

**Comment by KevCaz** [comment]
Hi @Noa164, sorry for the delay, I cannot reproduce it, is it solved on your end?

**Comment by Noa164** [comment]
Hello, it was solved thank you very much!

Noa
