### ISSUE TITLE
Objects mgNetwork & mgNetworkCollection

### ISSUE THREAD

**Issue by SteveViss** [ropensci/rmangal#12]
- [x] Create mgNetwork class (one network, all interactions at a specific location and time)
- [x] Create mgNetworkCollection (several networks of a dataset)

**Comment by SteveViss** [comment]
```mgNetwork

**Comment by SteveViss** [comment]
Structure des objets S3:
```
| -- class @mgNetworksCollections
        | -- class @mgNetwork
              | -- data.frame of edges
              | -- data.frame of nodes (see if expand to traits and taxonomy)
| attr('datasets') -- data.frame of datasets involved in the collection
| attr('references') -- data.frame of references involved in the collection
```

**Comment by SteveViss** [comment]
@KevCaz, let me know if that makes sense

**Comment by KevCaz** [comment]
It does, you could refine it latter anyway. Some time I feel like using attributes makes things harder for beginners (because you wonder how to access these data), a way is to add getters.

**Comment by SteveViss** [comment]
I was thinking to have getters functions. Like `getCitations()` will give you the bibtex store in the db for all references of the collection.
