### ISSUE TITLE
Vignettes

### ISSUE THREAD

**Issue by SteveViss** [ropensci/rmangal#13]
# List of comprehensive vignettes

1. How to list datasets?
2. How to retrieve networks from one and/or list of datasets?
3. How to retrieve all/specific networks?
4. Search over taxonomic name, retrieve networks which include this taxa
5. Search by location, used buffer, polygons to retrieve networks.
6. How to use the ids (bold, tsn, ncbi  etc.) to get extra taxonomic informations using taxize?

**Comment by SteveViss** [comment]
Should we write a general vignette instead of 6?

**Comment by KevCaz** [comment]
@SteveViss  what I like to do is:
1- An overview that would deal with what you've listed above
2- one or more study case where you combine your package with other (1, 2, ... vignettes)!
