### ISSUE TITLE
Development practices

### ISSUE THREAD

**Issue by SteveViss** [ropensci/rmangal#15]
- [x] Set CI/CD with travis
- [x] Protect master branch
- [x] Set/Init `tests` folder

**Comment by KevCaz** [comment]
As for now, the main branch is master, right? 
Let's protect it (Travis + Appveyor)!?

**Comment by SteveViss** [comment]
Yes, the main branch is master and protected @KevCaz .

**Comment by SteveViss** [comment]
In https://github.com/mangal-wg/rmangal/pull/43
