### ISSUE TITLE
Remove tibble dependency

### ISSUE THREAD

**Issue by KevCaz** [ropensci/rmangal#22]
If I am correct, `tibble` is only used for its well-thought print method. A way of using it without depending on tibble is to set the class of data frames to `c("tbl_df", "tbl", "data.frame")` then if `tibble` is loaded the tibble's print method will be used! I got the hint form Noam Ross (https://github.com/ropensci/software-review/issues/244).

**Comment by SteveViss** [comment]
Does that mean that `tibble` should be `suggest`?

**Comment by KevCaz** [comment]
Form https://cran.r-project.org/doc/manuals/r-release/R-exts.html

> The ‘Suggests’ field uses the same syntax as ‘Depends’ and lists packages that are not necessarily needed. This includes packages used only in examples, tests or vignettes (see Writing package vignettes), and packages loaded in the body of functions.

so if you want to include in vignettes/example, yes, otherwise, no.

**Comment by SteveViss** [comment]
I tried but I had to undo it... `sf` was complaining...

**Comment by KevCaz** [comment]
What was the error message?
Anyway, we can deal with this latter.

**Comment by KevCaz** [comment]
See #35
