### ISSUE TITLE
`list_datasets` from known datasets names

### ISSUE THREAD

**Issue by clementviolet** [ropensci/rmangal#25]
Hi guys,

I am testing the new functions of `rmangal`. Right now I am trying to retrieve datasets whom I know the name. According to the documentation `list_datasets()` can accept arguments to pass at the  `get_gen()` function.

So I want for exemple retrieve the dataset named `kemp_1977`, I try to do this:
```r
list_datasets(query = paste0("name=", "kemp_1977"))
```
Or I try to do something like this :
```r
list_datasets(query = list(name = "kemp_1997"))
```
Each time I got back the same error message

> Error in get_gen(endpoints()$dataset, query = list(q = search), ...) : 
  argument formel "query" correspondant à plusieurs arguments fournis

Is it a bug or am I doing something wrong?

**Comment by SteveViss** [comment]
Thanks @clementviolet, Try: 
```
devtools::install_github("mangal-wg/rmangal", ref = "init_dev")
rmangal::list_datasets(search="kemp")
```
the `search` argument is using the `q` parameter in the URI

**Comment by SteveViss** [comment]
But I have to fix this issue. `query` is called twice... But I'll try to find a way to pass a custom query argument to the `list_dataset()` function.

**Comment by clementviolet** [comment]
> Thanks @clementviolet, Try:
> 
> ```
> devtools::install_github("mangal-wg/rmangal", ref = "init_dev")
> rmangal::list_datasets(search="kemp")
> ```

It worked! Thanks for the help.
