### ISSUE TITLE
`mg_network()` 404 error

### ISSUE THREAD

**Issue by clementviolet** [ropensci/rmangal#26]
I had tested the `mg_network()` function before the pulled request #24 and it was working fine. Now I have updated my `rmangal` version, I got an error when I try to use this function :
```r
mg_network(16) # id of kemp_1977 datatset's
```
> API request failed: [404]
> FALSE

It seems that the function is stuck in a infinite  loop or something like this, because I need to abort the operation by hand. It is not a server issue beaucoup with my own function `clementviolet/get_mangal/`, I can access to this network and in Postman too.

**Comment by KevCaz** [comment]
May not be related to the PR as I get the same issue going back to one commit before PR: 

```
git checkout b34998e
```

```R
R> mg_network(16)
API request failed: [404]
FALSE
```

**Comment by clementviolet** [comment]
My bad, I could be an earlier build. I can not remember the date when I downloaded the package from the GitHub repo. Sorry...

**Comment by KevCaz** [comment]
Still something is wrong and need to be fixed :)

**Comment by SteveViss** [comment]
Found - The network id 16 doesn't exist. So the API send 404 not found, which make sense.
