### ISSUE TITLE
Error `list_datasets()` if some references field are NULL

### ISSUE THREAD

**Issue by clementviolet** [ropensci/rmangal#31]
Hi,

Maybe there were some recents change about db architecture, because `list_datasets()` is not working anymore.

When I tried to download a dataset (ie: `kemp_1977`) I got this:

```r
> list_datasets("kemp_1977")
```

> Found 1 dataset(s) for keywork: kemp_1977
> Erreur : All columns in a tibble must be 1d or 2d objects:
> * Column `doi` is NULL
> * Column `jstor` is NULL
> * Column `pmid` is NULL
> * Column `paper_url` is NULL
> Call `rlang::last_error()` to see a backtrace

See the return of the db below.
![Capture d’écran 2019-03-28 à 09 30 11](https://user-images.githubusercontent.com/22980442/55142202-5821ab80-513c-11e9-9e1c-4f09256a2927.png)

**Comment by KevCaz** [comment]
@SteveViss a simple way around is to replace the NULL by NA, it should work.

**Comment by KevCaz** [comment]
recursive function

```R
null_to_na <- function(x) {
    if (is.list(x)) {
        return(lapply(x, null_to_na))
    } else {
        return(ifelse(is.null(x), NA, x))
    }
}
```

Something efficient with a simple list: 

```R
myls <- list(v1 = 1, v2 = NULL)
myls[Position(is.null, myls)] <- NA 
```

**Comment by SteveViss** [comment]
This is because of changes on the data itself. I removed NA and null store as string instead of proper null. Thanks @KevCaz, your solution is working. I added within `coerce_body` function. I push the commit soon.

**Comment by SteveViss** [comment]
@clementviolet, this should work:

```
devtools::install_github("mangal-wg/rmangal", ref = "init_dev")
library(rmangal)
search_datasets("kemp_1977")
```

**Comment by KevCaz** [comment]
It works here! :smile:
