### ISSUE TITLE
search_datasets() purrr:map_() strange behavior

### ISSUE THREAD

**Issue by clementviolet** [ropensci/rmangal#32]
Hi,

I've just noticed a curious behavior of `search_datasets()`. When I tried to use `purrr::map_` the code execution is way more slow, see below the result of this benchmark:

```r
### Data

dataset_name <- c("fautin_1993", "ricciardi_2010", "edwards_1982")
 
#### First benchmark
tini <- Sys.time()

res_test_1 <- dataset_name %>%
  map_dfr(~search_datasets(search = x))
 
tfin <- Sys.time()

tfin - tini
```
> Time difference of 3.554202 mins
```r
### Second benchmark
tini <- Sys.time()

res_test_2 <- search_datasets(dataset_name[1])
```
> Found 1 dataset(s) for query: fautin_1993
```r
for(i in 2:length(dataset_name)){
  res_test_2 <- bind_rows(res_test_2, search_datasets(dataset_name[i]))
}
```
> Found 1 dataset(s) for query: ricciardi_2010
> Found 1 dataset(s) for query: edwards_1982
```r
tfin <- Sys.time()

tfin - tini
```
> Time difference of 2.091179 secs

I can't explain to myself this huge difference.

**Comment by SteveViss** [comment]
It's not an issue related to `rmangal`. Don't forget that you are benchmarking functions built on web services which the performance vary every ms: web traffic, load on the web server. So even `map_dfr` send twice will not return the same `tfin - tini`

**Comment by clementviolet** [comment]
@SteveViss I am aware that my benchmark is not as precise as a proper should be. What I wanted to demonstrate here is the huge difference in 2s and almost 4 min for the same number of requests.

I really think there's something wrong with it, since when I used `list_datasets()` I had better performance with `purr::map_` functions than with a for loop.

**Comment by SteveViss** [comment]
@clementviolet , you have no argument `search` in `search_datasets()`. The argument is `query`, see https://mangal-wg.github.io/rmangal/reference/search_datasets.html. So your first benchmarch query all datasets and your second return the 3 expected datasets.
