### ISSUE TITLE
output argument in `search_datasets()`

### ISSUE THREAD

**Issue by KevCaz** [ropensci/rmangal#40]
Are `raw` and `list`  useless in this context?

```R
R> res4 <- search_datasets(query = "2011", output = "list")
Found 1 datasets
Error in datasets[i, "id"] : no 'dimnames' attribute for array
R> res4 <- search_datasets(query = "2011", output = "raw")
Found 1 datasets
Error in datasets[i, "id"] : no 'dimnames' attribute for array
```

**Comment by SteveViss** [comment]
Yes @KevCaz, they are...  I will remove the ellipsis for all wrapping functions.

**Comment by SteveViss** [comment]
See https://github.com/mangal-wg/rmangal/commit/23756c6123c3154634be5b153f9e00ca483f9ba1

**Comment by SteveViss** [comment]
I cannot remove the `...` because of the `spatial` ouput. Can I just set a stop message telling the user that `list` and `raw` are disabled options in `search_*`. What do you think?

**Comment by KevCaz** [comment]
@SteveViss  I guess my question is then why do we need these options in `coerce_body()`

**Comment by KevCaz** [comment]
we could use:

```R
coerce_body <- function(x, resp, flatten, null_to_na = FALSE) {
  switch(
    x,
    data.frame = json_to_df(resp, flatten, null_to_na),
    spatial = mg_to_sf(json_to_df(resp, flatten, null_to_na))
  )
}
```

Why not?

**Comment by SteveViss** [comment]
Works for me !
