### ISSUE TITLE
merge in `search_interactions()`

### ISSUE THREAD

**Issue by KevCaz** [ropensci/rmangal#52]
So far the current approach is to add data frame in column which I think is confusing for users. 
This is the case for the `networks` column and the the additional appended when `expand_node = TRUE`. For the latter I propose something like : 

```R
if (expand_node) {
    tmp <- as.data.frame(get_singletons(endpoints()$node,
        interactions$node_from))
    names(tmp) <- paste0("node_from_", names(tmp))
    interactions <- cbind(tmp, interactions)
    #
    tmp <- as.data.frame(get_singletons(endpoints()$node,
        interactions$node_to))
    names(tmp) <- paste0("node_to_", names(tmp))
    interactions <- cbind(tmp, interactions)
 }
```

But there may be better option.

**Comment by SteveViss** [comment]
@KevCaz, Not sure if I agree with this one. I see and understand this valuable point, but I always get confused when data.frame as too much informations / columns. I prefer nested list or nested data.frame. I would suggest that we don't put effort into that and we will see if reviewers come with the same suggestion. What do you think?

**Comment by SteveViss** [comment]
Done in pull request #58
