### ISSUE TITLE
Citation file

### ISSUE THREAD

**Issue by clementviolet** [ropensci/rmangal#54]
Hi everyone!

I am writing my manuscript about my internship, and I would like to cite the rmangal package. I don't know how you want it to be cited, but I am making a proposal below.

```
@Manual{,
title = {rmangal},
author = {}, 
year = {2019},
note = {R package version 0.6.0},
url = {https://github.com/mangal-wg/rmangal}
}
```

I intentionally left blank the author field, because I don't know the order of the authors.

**Comment by SteveViss** [comment]
```
@Manual{,
    title = {rmangal - Explore the ecological interactions database},
    year = {2019},
    author = {Steve Vissault and Gabriel Bergeron and Benjamin Mercier and Clément Violet and Kevin 
     Cazelles and Dominique Gravel and Timothée Poisot}
}
```

**Comment by SteveViss** [comment]
When release, you will get it using `citation("rmangal")`
