### ISSUE TITLE
pkgdown: issue on inherit methods.

### ISSUE THREAD

**Issue by SteveViss** [ropensci/rmangal#60]
Hard to fix this one... don't know what it is.
@KevCaz , could you have a look if you have a moment.
Thanks !

```r
> pkgdown::build_article("rmangal")
Reading 'vignettes/rmangal.Rmd'
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function 'mapView' for signature '"tbl_df"'
```

**Comment by SteveViss** [comment]
Even more strange as `devtools::build_vignettes()` works

**Comment by KevCaz** [comment]
`devtools::build_site()` works on master.

**Comment by KevCaz** [comment]
```
R> pkgdown::build_article("rmangal")
Error: Can't find article called 'rmangal'
```

**Comment by KevCaz** [comment]
oops... wrong branch... my bad. But still, it works fine:

```
R> pkgdown::build_article("rmangal")
Reading 'vignettes/rmangal.Rmd'
Writing 'articles/rmangal.html'
```

**Comment by SteveViss** [comment]
This is so strange. I'll have to investigate. I had warning with igraph too. I updated `pkgdown`. I close this issue as it is related to my own environment.
