### ISSUE TITLE
data retrieval for network 19 never ends

### ISSUE THREAD

**Issue by KevCaz** [ropensci/rmangal#63]
reprex :

```
out  <- get_from_fkey_net(endpoints()$interaction, network_id = 19)
```

**Comment by SteveViss** [comment]
@KevCaz , Will end at some point. 15K interactions and 1.5K nodes take a while to fetch. I can easily prompt a message to enhance user experience if you want.

**Comment by SteveViss** [comment]
We just have to write a logical test based on: https://github.com/mangal-wg/rmangal/blob/master/R/zzz.R#L156

**Comment by KevCaz** [comment]
ok, so not a bug!

**Comment by KevCaz** [comment]
We should indicate the current status when `verbose` is set to TRUE.

**Comment by KevCaz** [comment]
Let's remember that **19** is a data set with tons of interaction and let's open a separate issue for what we need to do.
