### ISSUE TITLE
Remove sf from dependencies list

### ISSUE THREAD

**Issue by KevCaz** [ropensci/rmangal#83]
As suggested by the reviewer https://github.com/ropensci/software-review/issues/332#issuecomment-518006617 let's remove sf from the dependencies:

- [x] remove `search_networks_sf() `
- [x] remove associated tests
- [x] make an example in the vignette how to do this kind of sorting.

**Comment by SteveViss** [comment]
Related to d5a00d5

**Comment by SteveViss** [comment]
I choose to leave the function `search_network_sf()`. If a `sf` object is passed to the function and the package is not installed, then the user will receive an error recommending to install it.
