### ISSUE TITLE
Add reviewers in DESCRIPTION

### ISSUE THREAD

**Issue by KevCaz** [ropensci/rmangal#91]
Both reviewers agreed to do so and were very helpful, so let's add them! 

https://github.com/ropensci/software-review/issues/332

**Comment by KevCaz** [comment]
See cae8f017a8c0f3e15f8bf7017b9c5e5fda2c1373

**Comment by SteveViss** [comment]
Done in cae8f017a8c0f3e15f8bf7017b9c5e5fda2c1373
