### ISSUE TITLE
CRAN build error

### ISSUE THREAD

**Issue by SteveViss** [ropensci/rmangal#96]
**Deadline:** 2020-08-26
**Log:** https://cran.r-project.org/web/checks/check_results_rmangal.html
**Error**
```> test_check("rmangal")
-- 1. Error: expected behavior (@test-as.igraph.R#13) -------------------------
there is no package called 'tidygraph'```

**Comment by SteveViss** [comment]
```
PhantomJS not found. You can install it with webshot::install_phantomjs(). If it is installed, please make sure the phantomjs executable can be found via the PATH variable.
Quitting from lines 251-258 (rmangal.Rmd)
```

**Comment by SteveViss** [comment]
I'll not have time to investigate the problem before going into vacation (back on 31th). @KevCaz, do you know the implication for that? Will they remove the package from the CRAN? Should I write them a message asking to postpone the deadline?

**Comment by KevCaz** [comment]
Yes, the package will be removed from the CRAN. I can try to investigate tonight so you can just send the patch version. Otherwise, yes, you can write them. Worst case scenario, they remove the package from the CRAN and it'll be back once you've fixed it.

**Comment by KevCaz** [comment]
But @SteveViss, you should rather wait and see, the error is likely to be caused by tidyr that is failing on Debian with clang. 
https://cran.r-project.org/web/checks/check_results_tidygraph.html which I think is caused by a recent change in cpp11 (https://github.com/r-lib/cpp11/issues/88) and looks like it'll be fixed soon.

**Comment by SteveViss** [comment]
Ok, I'll wait until saturday and fix it.

**Comment by SteveViss** [comment]
There are still warnings on the build, but the error is gone.  I hope it will be all good...
Warnings are coming because `phantomJS` is not installed in the building environment. PhantomJS is needed since we're using `mapview` in our vignette. `mapview` (?) uses the `webshot` package to coerce the `html` to a `png`  (in order to be included in the PDF). Hope this makes sense. 

So should we remove the `mapview` function from our vignette and include a PNG by ourself in order to avoid those warnings from the CRAN? 

Do you know if they (the CRAN) still remove the package because of warnings?

**Comment by sckott** [comment]
Archived on CRAN now- need any help?

**Comment by KevCaz** [comment]
Hi @sckott, I'll have a quick look now. @SteveViss might be busy those days, so if I don't find what's wrong and if Steve doesn't have time, we would certainly appreciate your help.

**Comment by KevCaz** [comment]
The vignette seems to be the culprit. 
Specifically, line 204

```R
all_datasets <- search_datasets("")
```

which gives the following issue 

```R
Error in `$<-.data.frame`(`*tmp*`, networks, value = list(list(id = 12L,  : 
  replacement has 172 rows, data has 173
```

Turns out the problem is with petipa_1979:

```R
id        name                                                                                   description public               created_at               updated_at ref_id user_id
34 46 petipa_1979 Food web of pelagic communities of the southern seas of the USSR and in the tropical Pacific.   TRUE 2019-02-24T19:53:37.411Z 2019-02-24T19:53:37.411Z     47       3
```

@SteveViss said it would follow up on this tomorrow.

**Comment by SteveViss** [comment]
Found it: one dataset doesn't have networks which prevents `search_datasets("")` to return the `datasets` object because   `nrow(datasets) != length(network)`. I close this issue and open a new one more related.

**Comment by SteveViss** [comment]
In fact, this issue is not resolved. Will fix [this issue](https://github.com/ropensci/rmangal/issues/97) first and then go back on this one.

**Comment by SteveViss** [comment]
Follow up on CRAN submission. Result from the CRAN package check.

```
Thanks, we see:

Found the following (possibly) invalid URLs:
    URL: http://www.r-pkg.org/badges/version/rmangal (moved to https://www.r-pkg.org:443/badges/version/rmangal)
      From: README.md
      Status: 200
      Message: OK
    URL: https://docs.ropensci.org/rmangal (moved to https://docs.ropensci.org/rmangal/)
      From: DESCRIPTION
            man/rmangal.Rd
      Status: 200
      Message: OK
    URL: https://eol.org/
      From: man/search_taxonomy.Rd
      Status: Error
      Message: libcurl error code 28:
            Connection timed out after 60000 milliseconds
    URL: https://github.com/PoisotLab/Mangal.jl (moved to https://github.com/EcoJulia/Mangal.jl)
      From: inst/doc/rmangal.html
      Status: 200
      Message: OK
    URL: https://mangal.io/doc/api (moved to https://mangal.io/doc/api/)
      From: DESCRIPTION
      Status: 200
      Message: OK


Please change http --> https, add trailing slashes, or follow moved content as appropriate.


    URL: https://ropensci.github.io/rmangal/
      From: inst/CITATION
      Status: 404
      Message: Not Found

Please fix and resubmit.

```

**Comment by KevCaz** [comment]
Just need some tiny URL edits... I'll do it.

**Comment by KevCaz** [comment]
https://cran.r-project.org/web/packages/URL_checks.html

**Comment by KevCaz** [comment]
Don't understand what happended for eol 

```
$ curl -I -L https://eol.org/                          [10:08:06]
HTTP/1.1 200 OK
Date: Fri, 02 Oct 2020 14:08:07 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 0
Connection: keep-alive
X-Frame-Options: ALLOWALL
ETag: W/"54a73949b9ae7570655a7ccc535b3d1e"
Cache-Control: max-age=0, private, must-revalidate
Content-Security-Policy: 
Set-Cookie: last_regular_path=%2F; path=/
Set-Cookie: _eol_website_session=6Lt5jCAVIHxSX28tidFrdfYYqMS3U7JWkNmUNAak3NNjYap1N9%2FyK8w1vcvqnGVP05CQ7G5uNCh6%2Bh3aVnzIst2%2FTdMZLD7Bh7nstMvmhBrxg9i8CT51uVFoKPc0FpdJy%2B5Gp24clsmyO%2BTTveU%3D--CJjuNEv2p%2B9%2FYb5%2F--%2Fe2tkRECrFNs9RnPtMIjgg%3D%3D; path=/; HttpOnly
X-Request-Id: fdbcced3-a80c-44b8-9793-afa410c0a78b
X-Runtime: 0.131627
Age: 0
X-Cache: MISS
X-Cache-Hits: 0
```

**Comment by SteveViss** [comment]
Back on track
